chore: Update install-dev

diff --git a/install-dev b/install-dev
--- a/install-dev
+++ b/install-dev
@@ -1,7 +1,4 @@
 #!/bin/sh
-# WARN: This script is intended to be used only by the auther.
-# WARN: This script deletes currently installed milone-lang tools.
-#
 # Install milone command locally for development.
 #
 # See ./install for production.
@@ -16,30 +13,33 @@ BIN_DIR="$HOME/bin"
 MILONE_HOME="$HOME/.milone"
 
 # ------------------------------------------------
+# Prepare
+# ------------------------------------------------
+
+# Trap error.
+trap 'test $? -ne 0 && echo "install-dev: Installation failed."' EXIT
+
+# ------------------------------------------------
 # Process
 # ------------------------------------------------
 
 ./uninstall
 
-# Ensure directory exists.
-mkdir -p "$MILONE_HOME/bin"
+# Ensure directories exist.
+mkdir -p "$MILONE_HOME/bin/milone_dotnet"
+mkdir -p "$MILONE_HOME/bin/milone_lsp"
 
-# Link native executable.
-ln -bfs "$PWD/target/milone" "$MILONE_HOME/milone_native"
+# Make symbolic links.
+ln -fs "$PWD/target/milone" "$MILONE_HOME/milone_native"
+ln -fs "$PWD/MiloneLang/bin/Debug/net5.0/MiloneLang" "$MILONE_HOME/bin/milone_dotnet/MiloneLang"
+ln -fs "$PWD/milone_lsp/bin/Debug/net5.0/MiloneLsp" "$MILONE_HOME/bin/milone_lsp/MiloneLsp"
+ln -fs "$PWD/runtime" "$MILONE_HOME/runtime"
+ln -fs "$PWD/milone_libs" "$MILONE_HOME/milone_libs"
 
-# Link milone-dotnet.
-ln -bfs "$PWD/MiloneLang/bin/Debug/net5.0/MiloneLang" "$MILONE_HOME/bin/milone_dotnet/MiloneLang"
+# Record version number and commit hash.
+VERSION="$(target/milone --version) $(git rev-parse HEAD)"
 
-# Link LSP server.
-ln -bfs "$PWD/milone_lsp/bin/Debug/net5.0/MiloneLsp" "$MILONE_HOME/bin/milone_lsp/MiloneLsp"
-
-# Link runtime.
-test -d "$MILONE_HOME/runtime" && rm "$MILONE_HOME/runtime"
-ln -sf "$PWD/runtime" "$MILONE_HOME/runtime"
-
-# Link milone_libs.
-test -d "$MILONE_HOME/milone_libs" && rm "$MILONE_HOME/milone_libs"
-ln -sf "$PWD/milone_libs" "$MILONE_HOME/milone_libs"
+echo $VERSION >"$MILONE_HOME/version"
 
 # ------------------------------------------------
 # milone script
@@ -47,6 +47,7 @@ ln -sf "$PWD/milone_libs" "$MILONE_HOME/milone_libs"
 
 cat >"$BIN_DIR/milone" <<'END'
 #!/bin/sh
+# Execute milone and fallback to .NET version on error.
 
 # Try run native version.
 MILONE_HOME="{{ MILONE_HOME }}" "{{ MILONE_HOME }}/milone_native" "$@"
@@ -67,18 +68,4 @@ sed -i "s:{{ MILONE_HOME }}:$MILONE_HOME:g" "$BIN_DIR/milone"
 
 chmod +x "$BIN_DIR/milone"
 
-# ------------------------------------------------
-# milone-gcc script
-# ------------------------------------------------
-
-cat >"$BIN_DIR/milone-gcc" <<'END'
-#!/bin/sh
-
-milone "$@" | gcc -std=c11 -O2 -I "{{ MILONE_HOME }}/runtime" "{{ MILONE_HOME }}/runtime/milone.c" -x c -
-END
-
-sed -i "s:{{ MILONE_HOME }}:$MILONE_HOME:g" "$BIN_DIR/milone-gcc"
-
-chmod +x "$BIN_DIR/milone-gcc"
-
-echo 'OK'
+echo "install-dev: milone-lang v$VERSION is installed successfully."
