chore: Update scripts

diff --git a/integration-test b/integration-test
--- a/integration-test
+++ b/integration-test
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Perform single case integration test.
+# Perform single integration test case.
 # USAGE: integration-test name milone verbosity
 
 set -u
@@ -10,28 +10,28 @@ then
     exit 0
 fi
 
-CFLAGS='-std=c11 -I runtime -Wall -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label -O1'
+CFLAGS='-std=c11 -O2 -I boot/runtime -Wall -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label'
 
-NAME=$(basename $1)
-MILONE=${2:-'./milone_netcore'}
+NAME=$(basename "$1")
+MILONE=${2:-'boot/MiloneLang/bin/Debug/netcoreapp3.1/MiloneLang'}
 VERBOSITY=${3:-'-q'}
 
-if [[ -z $1 ]]
-then
-    echo "Unknown test case '$NAME'." >&2
-    exit 1
-fi
-
-DIR=$(find tests/*/$NAME -type d | head -n 1)
+DIR=$(find 'boot/tests' -type d | grep -e "\\b$NAME$" | head -n 1)
 TEST_SRC="$DIR/$NAME.fs"
 TEST_OUTX="$DIR/$NAME.out"
-TEST_C="$DIR/~$NAME.c"
-TEST_EXE="$DIR/~$NAME"
-TEST_OUTA="$DIR/~$NAME.out"
+TEST_C="$DIR/$NAME.c"
+TEST_EXE="$DIR/$NAME.generated.exe"
+TEST_OUTA="$DIR/$NAME.generated.out"
 
-if [[ ! -f $TEST_SRC || ! -f $TEST_OUTX ]]
+if test ! -f $TEST_OUTX
 then
-    echo "Missing '$TEST_SRC' or '$TEST_OUTX'" >&2
+    echo '$? = 0' >$TEST_OUTX
+fi
+
+if test ! -f $TEST_SRC
+then
+    echo "Missing '$TEST_SRC'." >&2
+    touch $TEST_SRC
     exit 0
 fi
 
@@ -40,31 +40,31 @@ echo -n "$NAME..." >&2
 # Build with milone-lang compiler.
 MILONE_CMD="$MILONE $VERBOSITY $DIR"
 
-if [[ $VERBOSITY = '-v' ]]
+if test $VERBOSITY = '-v'
 then
     echo "+ $MILONE_CMD" >&2
 fi
 
-MILONE_HOME=$PWD/.. $MILONE_CMD >$TEST_C
-if [[ $? != 0 ]]
+MILONE_HOME=$PWD $MILONE_CMD >$TEST_C
+if test $? -ne 0
 then
     echo 'milone-lang compile error.' >$TEST_OUTA
 else
     # Build with C compiler.
     CC_CMD="gcc $CFLAGS $TEST_C -o $TEST_EXE"
 
-    if [[ $VERBOSITY = '-v' ]]
+    if test $VERBOSITY = '-v'
     then
         echo "+ $CC_CMD" >&2
     fi
 
     $CC_CMD
-    if [[ $? != 0 ]]
+    if test $? -ne 0
     then
         echo 'gcc compile error.' >$TEST_OUTA
     else
         # Execute the binary.
-        if [[ $VERBOSITY = '-v' ]]
+        if test $VERBOSITY = '-v'
         then
             echo "+ $TEST_EXE" >&2
         fi
