feat: Don't stop workflow on error as possible
And task can now check if a code causes compile error.

diff --git a/boot/task b/boot/task
--- a/boot/task
+++ b/boot/task
@@ -22,7 +22,18 @@ compile() {
 
     mkdir -p tmp
     cat $m | dotnet run -p MiloneLang -- "$2" - >$c
+    if [[ $? != 0 ]]
+    then
+        echo 'milone-lang compile error.'
+        return 1
+    fi
+
     gcc -std=c11 -Wall -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label $c -o $app
+    if [[ $? != 0 ]]
+    then
+        echo 'gcc compile error.'
+        return 1
+    fi
 }
 
 # Runs a milone code
@@ -39,12 +50,22 @@ integ() {
     out="$(locate $name)/~$name.out"
     expected="$(locate $name)/$name.out"
 
-    >&2 echo -n "$name ... "
-    compile "$name" -q
-
     set +e
-    $app >$out
-    echo '$? = '$? >>$out
+
+    >&2 echo -n "$name ... "
+
+    # Compile.
+    compile "$name" -q >$out
+    comple_exit_code=$?
+
+    # Run.
+    if [[ $comple_exit_code = 0 ]]
+    then
+        $app >>$out
+        echo '$? = '$? >>$out
+    fi
+
+    # Verify output and exit code.
     if diff -q $out $expected
     then
         >&2 echo "✔ ok"
@@ -52,6 +73,7 @@ integ() {
         >&2 echo "✘ FAILED"
         echo -n '*'
     fi
+
     set -e
 }
 
